### ISSUE TITLE
Implementation of Query-Key embedding not found

### ISSUE THREAD

**Issue by ZichengDuan** [EnVision-Research/MotionInversion#12]
Dear author, thanks for presenting this inspiring work, the code runs smoothly following the instructions. However, I found that there seems to be no implementation for Query-Key embedding mentioned in the paper. If I understand the algorithm correctly, the hidden_states latent should also be manipulated in the temporal attention block, similarly to that in Value Embedding, according to the code below:
https://github.com/EnVision-Research/MotionInversion/blob/31ed7fb0f6f4a669832a550a2188305cade89416/attn_ctrl.py#L188-L189
The hidden states seem to be totally untouched, moreover, I also have difficulties locating the registration for QK embeddings.

Could you please provide instructions on these questions? I sincerely appreciate your kind help, thanks in advance.

**Comment by ZichengDuan** [comment]
Closed as the QK Emb registration is found at:
https://github.com/EnVision-Research/MotionInversion/blob/31ed7fb0f6f4a669832a550a2188305cade89416/models/unet/motion_embeddings.py#L176
and
https://github.com/EnVision-Research/MotionInversion/blob/31ed7fb0f6f4a669832a550a2188305cade89416/models/unet/motion_embeddings.py#L216

Meanwhile, the inference is found at:
https://github.com/EnVision-Research/MotionInversion/blob/31ed7fb0f6f4a669832a550a2188305cade89416/attn_ctrl.py#L59

**Comment by tanshuai0219** [comment]
I am also interested in where the implementation of Value embedding is.
